[2024-09-11T03:38:38.926+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-11T03:38:39.087+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Start_Pipeline01.query_data_from_mongo manual__2024-09-11T03:38:37.634020+00:00 [queued]>
[2024-09-11T03:38:39.096+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Start_Pipeline01.query_data_from_mongo manual__2024-09-11T03:38:37.634020+00:00 [queued]>
[2024-09-11T03:38:39.097+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 2
[2024-09-11T03:38:39.110+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): query_data_from_mongo> on 2024-09-11 03:38:37.634020+00:00
[2024-09-11T03:38:39.118+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4048) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-09-11T03:38:39.118+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Start_Pipeline01', 'query_data_from_mongo', 'manual__2024-09-11T03:38:37.634020+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/data-prep-for-model.py', '--cfg-path', '/tmp/tmpm2i4_x1f']
[2024-09-11T03:38:39.120+0000] {standard_task_runner.py:72} INFO - Started process 4055 to run task
[2024-09-11T03:38:39.120+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask query_data_from_mongo
[2024-09-11T03:38:39.167+0000] {task_command.py:467} INFO - Running <TaskInstance: Start_Pipeline01.query_data_from_mongo manual__2024-09-11T03:38:37.634020+00:00 [running]> on host dca6f81c3bd4
[2024-09-11T03:38:39.248+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Start_Pipeline01' AIRFLOW_CTX_TASK_ID='query_data_from_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T03:38:37.634020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T03:38:37.634020+00:00'
[2024-09-11T03:38:39.249+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-11T03:38:39.310+0000] {transport.py:1923} INFO - Connected (version 2.0, client OpenSSH_8.2p1)
[2024-09-11T03:38:39.368+0000] {transport.py:1923} INFO - Authentication (password) successful!
[2024-09-11T03:38:42.307+0000] {taskinstance.py:3301} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-prep-for-model.py", line 25, in query_data_from_mongo
    directory = os.path.dirname(file_path)
                                ^^^^^^^^^
UnboundLocalError: cannot access local variable 'file_path' where it is not associated with a value
[2024-09-11T03:38:42.323+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=Start_Pipeline01, task_id=query_data_from_mongo, run_id=manual__2024-09-11T03:38:37.634020+00:00, execution_date=20240911T033837, start_date=20240911T033839, end_date=20240911T033842
[2024-09-11T03:38:42.341+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-11T03:38:42.342+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 19 for task query_data_from_mongo (cannot access local variable 'file_path' where it is not associated with a value; 4055)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2995, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3149, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3173, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data-prep-for-model.py", line 25, in query_data_from_mongo
    directory = os.path.dirname(file_path)
                                ^^^^^^^^^
UnboundLocalError: cannot access local variable 'file_path' where it is not associated with a value
[2024-09-11T03:38:42.392+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 1
[2024-09-11T03:38:42.411+0000] {taskinstance.py:3891} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-11T03:38:42.414+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
